name: 'Checkout mono repository'
on:
  workflow_dispatch

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            01-bootstrap/*
